#!/usr/bin/env python

from os.path import expanduser
from time import sleep
import sys

# finds the user directory ($HOME)
HOME = expanduser('~')

with open(HOME+'/.config/neofetch/neofetch_display') as f:
	for line in f:
		for c in line:
			print(c, end='', flush=True); sleep(0.00045);
